### ISSUE TITLE
一份测试

### ISSUE THREAD

**Issue by fewtime** [huangyanhui/lawDocSearch#30]
# 说明
基于 #29 测试

[x] -> 除共同错误外未发现其它错误
[] -> 除共同错误外，还存在其它错误

# 目录

1.  [共同错误](#org13c8792)
2.  [单纯搜索](#orgb10b353)
    1.  [简单条件](#org330dcbf)
    2.  [复合条件](#org60de489)
3.  [搜索 + 结果中搜索](#org2760501)
4.  [搜索 + 聚类搜索](#org6fec2a3)
    1.  [单层聚类](#org84bc36c)
    2.  [多层聚类](#org3b00f58)
        1.  [共同错误](#org5d3c27d)
        2.  [测试](#org5a8912d)
5.  [小标签](#orgf4dbc29)
6.  [详情页](#orge0fe01c)

<a id="org13c8792"></a>

# 共同错误

1.  加载更多后小标签消失
2.  小标签的 **同域搜索** 和 **顺序搜索** 表达错误

<a id="orgb10b353"></a>

# 单纯搜索

<a id="org330dcbf"></a>

## 简单条件

[x] 杀人

[ ] !杀人

1.  直接崩了，提示错误

> KeyError at /indexsearch ('highlight')

[ ] 王~杀人

1.  小标签中显示为 王~杀人~（同域搜索）

[ ] 李>杀人

1.  小标签中显示为 李>杀人（顺序搜索）

<a id="org60de489"></a>

## 复合条件

[x]杀人 放火

1.  点击加载更多后，小标签消失

[x] !杀人 !放火

1.  直接崩了，提示错误

> KeyError at /indexsearch ('highlight')

[x] 李~杀人~刑事

1.  小标签中显示为 李~杀人~刑事~（同域搜索）
2.  点击加载更多后，小标签消失

[x] 李>杀人>刑事

1.  小标签中显示为 李>杀人>刑事>（顺序搜索）
2.  点击加载更多后，小标签消失

<a id="org2760501"></a>

# 搜索 + 结果中搜索

[x]杀人 -> 王

[x]杀人 -> !王

1.  小标签没有消失（神奇）

[ ]杀人 -> 王~故意

1.  小标签显示: 王~故意~（同域搜索）

[ ]杀人 -> 王>刑事

1.  小标签显示: 王~故意~（顺序搜索）

<a id="org6fec2a3"></a>

# 搜索 + 聚类搜索

<a id="org84bc36c"></a>

## 单层聚类

[x] 杀人 -> 基层法院

[x]杀人 -> 刑事裁定书

[ ]杀人 -> 2014

1.  案号处的年份（2014）高亮错误，显示：

>（<span style="color:red">2014</span>）连刑初字第00030号

[x]杀人 -> 故意杀人罪

[x]杀人 -> 山东

[x]杀人 -> 一审

<a id="org3b00f58"></a>

## 多层聚类

<a id="org5d3c27d"></a>

### 共同错误

1.  案号处的年份（2014）高亮错误，显示：

>（<span style="color:red">2014</span>）连刑初字第00030号

<a id="org5a8912d"></a>

### 测试

[x] 杀人 -> 基层法院 -> 2014
[x] 杀人 -> 基层法院 -> 2014 -> 山东
[x] 杀人 -> 基层法院 -> 2014 -> 山东 -> 一审
[x] 杀人 -> 基层法院 -> 2014 -> 山东 -> 一审 -> 故意杀人
[x] 杀人 -> 基层法院 -> 2014 -> 山东 -> 一审 -> 故意杀人 -> 刑事裁定书

<a id="orgf4dbc29"></a>

# 小标签

[x] 杀人 -> 点击（杀人）

[x] 杀人 -> 李 -> （点击）杀人

[x] 杀人 -> 李 -> （点击）李

[x] 杀人 -> 李 -> （点击）李 -> （点击）杀人

[x] 杀人 -> 李 -> （点击）杀人 -> （点击）李

[ ] 杀人 -> !李 -> （点击）!李

1.  异常

> ValueError at /searchlabel
> list.remove(x): x not in list

[ ] 杀人 -> !李 -> （点击）杀人

1.  异常

> KeyError at /searchlabel
> 'highlight'

[x] 杀人 -> 王~故意 -> （点击）王~故意

[x] 杀人 -> 王~故意 -> （点击）杀人

[x] 杀人 -> 王>刑事 -> （点击）王>刑事

[x] 杀人 -> 王>刑事 -> （点击）杀人

<a id="orge0fe01c"></a>

# 详情页

1.  页面标题为 `Title`
2.  下载按钮的位置别扭
3.  点击错误会出现下列错误

> OSError at /download
> No wkhtmltopdf executable found: "D:\wkhtmltopdf\bin\wkhtmltopdf.exe"
> If this file exists please check that this process can read it. Otherwise please install wkhtmltopdf - <https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf>

**Comment by fewtime** [comment]
#31 小标签的 同域搜索 和 顺序搜索 表达错误

**Comment by fewtime** [comment]
[83a949e](https://github.com/huangyanhui/lawDocSearch/pull/31/commits/83a949e13760fa9e72b17c8887ad6b82379ebbb1) 修复 加载更多 小标签消失

**Comment by huangyanhui** [comment]
"C:\Program Files\JetBrains\PyCharm 2017.2.3\bin\runnerw.exe" C:\Users\huang\Anaconda3\python.exe C:/Users/huang/PycharmProjects/lawDocSearch/manage.py runserver 8000
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): account.
Run 'python manage.py migrate' to apply them.
March 16, 2018 - 10:48:49
Django version 2.0.3, using settings 'lawDocSearch.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\huang\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\huang\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\huang\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\huang\PycharmProjects\lawDocSearch\lawDoc\views.py", line 28, in index
    identity = request.session['identity']
  File "C:\Users\huang\Anaconda3\lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
KeyError: 'identity'
[16/Mar/2018 10:48:50] "GET / HTTP/1.1" 500 69113
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\huang\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\huang\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\huang\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\huang\PycharmProjects\lawDocSearch\lawDoc\views.py", line 28, in index
    identity = request.session['identity']
  File "C:\Users\huang\Anaconda3\lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
KeyError: 'identity'
[16/Mar/2018 10:50:21] "GET / HTTP/1.1" 500 69114

**Comment by fewtime** [comment]
@huangyanhui 

在 Django shell 中运行

from django.contrib.sessions.models import Session

Session.objects.all().delete()
